# Generated by Django 5.0.4 on 2024-04-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='sub_title',
            new_name='sub_title1',
        ),
        migrations.AddField(
            model_name='carousel',
            name='sub_title2',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
